All:
	mvn compile
	java -classpath ./target/classes Compiler target/classes/nod.cs

cmpl:
	mvn compile

startNod:
	java -classpath ./target/classes Compiler target/classes/nod.cs

startSearch:
	java -classpath ./target/classes Compiler target/classes/search.cs
	
startMin:
	java -classpath ./target/classes Compiler target/classes/min.cs
	